all:
	javac -d classes/ -cp classes/ EmptyTreeException.java
	javac -d classes/ -cp classes/ IllegalIDException.java
	javac -d classes/ -cp classes/ NotEmptyException.java
	javac -d classes/ -cp classes/ OrgHierarchyInterface.java
	javac -d classes/ -cp classes/ OrgHierarchy.java
	javac -d classes/ -cp classes/ Tester3_9.java
	java -cp classes/ Tester3_9

clean:
	rm classes/EmptyTreeException.class classes/IllegalIDException.class ../classes/NotEmptyException.class classes/OrgHierarchyInterface.class classes/OrgHierarchy.class classes/Tester.class
 
